/** 四年级纪录片库：工作日 A / 周末 B；四格 + 审美/商业肌肉
 * play: stable=正版页 | ok=可用公开源 | search=仅搜索投稿 | risk=孩子端常打不开
 */
window.DOC_CATALOG = {
  grade: 4,
  title: "四年级 · 纪录片小探险家",
  categories: [
    { id: "drive", name: "自驱力", short: "自驱", muscles: ["意志", "选择"] },
    { id: "nature", name: "自然科学", short: "自然", muscles: ["人体", "生物"] },
    { id: "human", name: "人文历史", short: "人文", muscles: ["叙事", "审美"] },
    { id: "finance", name: "理财经济", short: "理财", muscles: ["数理", "商业"] },
  ],
  rotation: ["drive", "nature", "human", "finance"],
  titles: [
    {
      id: "xiaoxiao",
      title: "小小少年",
      category: "drive",
      slot: "A",
      role: "main",
      duration: "约 36 分钟 × 6 集",
      episodeHint: "当晚只看 1 集",
      muscle: "意志",
      link: "https://www.bilibili.com/bangumi/play/ep391685",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧，全集完结；高清常需大会员",
      mapPin: "同龄人 · 痴迷与坚持",
    },
    {
      id: "kipchoge",
      title: "基普乔格：最后的里程碑",
      category: "drive",
      slot: "B",
      role: "must",
      duration: "电影约 85–90 分钟",
      episodeHint: "周末一部",
      muscle: "意志",
      link: "https://www.bilibili.com/video/BV1Ca411n74Z/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "投稿直链；清晰度与是否下架不保证",
      mapPin: "维也纳 · 人类没有极限",
      parentNote: "无正版页，投稿可能下架",
    },
    {
      id: "richpoor",
      title: "富哥哥，穷弟弟",
      category: "drive",
      slot: "B",
      role: "must",
      alsoCategory: "finance",
      duration: "约 47–60 分钟",
      episodeHint: "家长先看再陪看",
      muscle: "选择",
      link: "https://www.bilibili.com/video/BV1Ys4y1h7Ph/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "投稿直链；请先确认完整版",
      mapPin: "伦敦 · 选择与习性",
      parentNote: "阶层对照，非鸡汤",
    },
    {
      id: "schoolroad",
      title: "翻山涉水上学路",
      category: "drive",
      slot: "B",
      role: "side",
      duration: "约 45–50 分钟",
      episodeHint: "周末加餐",
      muscle: "意志",
      link: "https://www.bilibili.com/video/BV1x3411q7qb/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "央视译制合集（第1–2季）；只挑一集看",
      mapPin: "世界各地 · 上学路",
    },
    {
      id: "crow",
      title: "像乌鸦一样思考",
      category: "nature",
      slot: "A",
      role: "main",
      duration: "约 10 分钟 × 20 集",
      episodeHint: "一晚 1–2 集",
      muscle: "生物",
      link: "https://open.163.com/newview/movie/free?pid=MEHLI0563&mid=MEHLMNO8M",
      linkLabel: "网易公开课",
      play: "ok",
      playNote: "公开课目录；B 站也有中配投稿，画质看版本",
      mapPin: "观察 · 假设 · 实验",
    },
    {
      id: "planet",
      title: "地球脉动 第一季",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50–60 分钟 × 11 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      link: "https://www.bilibili.com/bangumi/play/ep121262",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧；高清常见需大会员",
      mapPin: "从极地到深海",
    },
    {
      id: "humanbody",
      title: "人体奥秘",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 4 集",
      episodeHint: "第 1、4 集家长陪看",
      muscle: "人体",
      link: "https://www.bilibili.com/video/BV1Sg411371W/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "BBC 原片投稿现少；改用同题材 PBS《人体大惊奇》6 集合集，挑 1 集",
      mapPin: "身体内部",
      parentNote: "胚胎与临终类镜头仍可能出现，第 1、4 类集家长陪看",
    },
    {
      id: "life",
      title: "生命",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 10 集",
      episodeHint: "先看植物、鸟、鱼",
      muscle: "生物",
      link: "https://www.bilibili.com/bangumi/play/ep118932",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧；高清可能要会员",
      mapPin: "物种怎么活",
    },
    {
      id: "wonders",
      title: "生命的奇迹",
      category: "nature",
      slot: "B",
      role: "side",
      duration: "约 48–60 分钟 × 5 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      link: "https://www.bilibili.com/video/BV1Uw411d7xw/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "国语合集直链；周末只看 1 集",
      mapPin: "生命是什么",
    },
    {
      id: "guobao",
      title: "如果国宝会说话",
      category: "human",
      slot: "A",
      role: "main",
      duration: "5 分钟，一晚 2–3 集",
      episodeHint: "打包 2–3 集",
      muscle: "审美",
      link: "https://www.bilibili.com/bangumi/play/ep165008",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧，页面标高清",
      mapPin: "博物馆 · 形与工艺",
    },
    {
      id: "designah",
      title: "啊！设计",
      category: "human",
      slot: "A",
      role: "side",
      duration: "约 15 分钟",
      episodeHint: "工作日加餐",
      muscle: "审美",
      link: "https://www.bilibili.com/video/BV1hwKfzmEr4/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "60 集合集直链；当晚只看 1 集",
      mapPin: "观察 · 拆解",
    },
    {
      id: "aerial",
      title: "航拍中国 第一季",
      category: "human",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 6 集",
      episodeHint: "周末 1 集",
      muscle: "叙事",
      link: "https://tv.cctv.com/2016/12/28/VIDALOmjxOZe51NjntPvOI00161228.shtml",
      linkLabel: "央视网",
      play: "stable",
      playNote: "央视网官方；手机建议央视影音 App",
      mapPin: "中国大地 · 构图",
    },
    {
      id: "dimensions",
      title: "维度：数学漫步（第1–2章）",
      category: "finance",
      slot: "A",
      role: "main",
      duration: "约 14 分钟 / 章",
      episodeHint: "只看二维、三维",
      muscle: "数理",
      link: "https://www.dimensions-math.org/Dim_ZH_si.htm",
      linkLabel: "官网免费正片",
      play: "stable",
      playNote: "创作共用，官网可看可下，画质清晰",
      mapPin: "空间直觉",
    },
    {
      id: "econmachine",
      title: "经济机器是怎样运行的",
      category: "finance",
      slot: "A",
      role: "main",
      duration: "约 30 分钟 × 1",
      episodeHint: "可工作日看完",
      muscle: "商业",
      link: "https://www.bilibili.com/video/BV1HA411j7vH/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "约 30 分钟完整投稿；有字幕",
      mapPin: "交易 · 信贷 · 周期",
      altLink: "https://www.youtube.com/watch?v=rFV7wdEX-Mo",
      altLabel: "YouTube（备）",
    },
    {
      id: "logicjoy",
      title: "逻辑的乐趣",
      category: "finance",
      slot: "B",
      role: "side",
      duration: "约 60 分钟",
      episodeHint: "可拆两晚",
      muscle: "数理",
      link: "https://www.bilibili.com/video/BV1W3411y7Dc/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "约 60 分钟完整投稿",
      mapPin: "逻辑是什么",
    },
    {
      id: "mathstory",
      title: "数学的故事（第1–2集）",
      category: "finance",
      slot: "B",
      role: "side",
      duration: "约 60 分钟 × 4（四年级看前 2）",
      episodeHint: "宇宙的语言 · 东方奇才",
      muscle: "数理",
      link: "https://www.bilibili.com/video/BV1DZ421H7it/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "第1集《宇宙的语言》直链；第2集可另找东方数学篇",
      mapPin: "数学史入口",
      altLink: "https://www.bilibili.com/video/BV1oa411E7wd/",
      altLabel: "第2集入口",
    },
  ],
};
