/** 四年级纪录片库：工作日 A / 周末 B；四格 + 审美/商业肌肉
 * play: stable=正版页 | ok=可用公开源 | search=仅搜索投稿 | risk=孩子端常打不开
 * blurb: 卡片外可见的一句话简介，方便选片
 * 每部只归一个 category；盖印下沉到集（episodes[]）。
 * episode: { id, n, title, blurb, duration?, link?, hints?[] }
 * 无 episodes 的片子，界面会自动当成「整部 / 1 集」打卡。
 */
window.DOC_CATALOG = {
  grade: 4,
  title: "四年级 · 纪录片小探险家",
  categories: [
    { id: "drive", name: "自驱力", short: "自驱", muscles: ["意志", "选择"] },
    { id: "nature", name: "自然科学", short: "自然", muscles: ["人体", "生物"] },
    { id: "human", name: "人文历史", short: "人文", muscles: ["叙事", "审美"] },
    { id: "finance", name: "理财经济", short: "理财", muscles: ["数理", "商业"] },
  ],
  rotation: ["drive", "nature", "human", "finance"],
  titles: [
    {
      id: "xiaoxiao",
      title: "小小少年",
      category: "drive",
      slot: "A",
      role: "main",
      duration: "约 36 分钟 × 6 集",
      episodeHint: "当晚只看 1 集",
      muscle: "意志",
      blurb: "六个同龄孩子各自痴迷一件事：练习、失败、再来。看别人怎么把热爱熬成习惯。",
      link: "https://www.bilibili.com/bangumi/play/ep391685",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧，全集完结；高清常需大会员",
      mapPin: "同龄人 · 痴迷与坚持",
    },
    {
      id: "kipchoge",
      title: "基普乔格：最后的里程碑",
      category: "drive",
      slot: "B",
      role: "must",
      duration: "电影约 85–90 分钟",
      episodeHint: "周末一部",
      muscle: "意志",
      blurb: "马拉松王者挑战「两小时内跑完」。不是鸡汤，是训练、团队和「人类没有极限」。",
      link: "https://www.bilibili.com/video/BV1Ca411n74Z/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "投稿直链；清晰度与是否下架不保证",
      mapPin: "维也纳 · 人类没有极限",
      parentNote: "无正版页，投稿可能下架",
    },
    {
      id: "richpoor",
      title: "富哥哥，穷弟弟",
      category: "drive",
      slot: "B",
      role: "must",
      duration: "约 47–60 分钟",
      episodeHint: "家长先看再陪看",
      muscle: "选择",
      blurb: "一对兄弟互换生活八天：钱、习惯、选择如何把人生推到两端。主归自驱；家长陪看讨论。",
      link: "https://www.bilibili.com/video/BV1Ys4y1h7Ph/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "投稿直链；请先确认完整版",
      mapPin: "伦敦 · 选择与习性",
      parentNote: "阶层对照，非鸡汤",
    },
    {
      id: "schoolroad",
      title: "翻山涉水上学路",
      category: "drive",
      slot: "B",
      role: "side",
      duration: "约 45–50 分钟",
      episodeHint: "周末加餐 · 只挑 1 集",
      muscle: "意志",
      blurb: "世界各地孩子为上学翻山、过河、走冰面。看「想去学校」能有多认真。",
      link: "https://www.bilibili.com/video/BV1x3411q7qb/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "央视译制合集（第1–2季）；只挑一集看",
      mapPin: "世界各地 · 上学路",
    },
    {
      id: "crow",
      title: "像乌鸦一样思考",
      category: "nature",
      slot: "A",
      role: "main",
      duration: "约 10 分钟 × 20 集",
      episodeHint: "一晚 1–2 集",
      muscle: "生物",
      blurb: "跟着乌鸦学科学方法：观察、提出假设、做实验。短、好玩，适合工作日。",
      link: "https://open.163.com/newview/movie/free?pid=MEHLI0563&mid=MEHLMNO8M",
      linkLabel: "网易公开课",
      play: "ok",
      playNote: "公开课目录；B 站也有中配投稿，画质看版本",
      mapPin: "观察 · 假设 · 实验",
    },
    {
      id: "bigscience",
      title: "大科学实验",
      category: "nature",
      slot: "A",
      role: "side",
      duration: "约 10 分钟 × 多集",
      episodeHint: "一晚 1 集",
      muscle: "生物",
      blurb: "准备—实验—验证：声音有多快、太阳能做饭。短实验片，和乌鸦同一条「动手想」的线。",
      link: "https://www.bilibili.com/video/BV1AU4y1p7o5/?p=1",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "NHK 中字合集，35 集分P；先看前几集即可",
      mapPin: "实验 · 验证",
      episodes: [
        { id: "bigscience-1", n: 1, title: "声音的速度", blurb: "声音跑得有多快？用实验「看见」声音。", duration: "约 10 分钟", link: "https://www.bilibili.com/video/BV1AU4y1p7o5/?p=1", hints: ["声音", "速度", "实验"] },
        { id: "bigscience-2", n: 2, title: "飞翔的鲸鱼", blurb: "一个大胆实验：如果……会怎样？", duration: "约 10 分钟", link: "https://www.bilibili.com/video/BV1AU4y1p7o5/?p=2", hints: ["假设", "规模", "想象"] },
        { id: "bigscience-3", n: 3, title: "杯子神奇的力量", blurb: "日常杯子里的力：压强、吸力怎么来。", duration: "约 10 分钟", link: "https://www.bilibili.com/video/BV1AU4y1p7o5/?p=3", hints: ["压强", "杯子", "日常"] },
        { id: "bigscience-4", n: 4, title: "太阳能做饭", blurb: "阳光能不能煮熟饭？把能量聚起来。", duration: "约 10 分钟", link: "https://www.bilibili.com/video/BV1AU4y1p7o5/?p=4", hints: ["太阳能", "聚焦", "能量"] },
        { id: "bigscience-5", n: 5, title: "高速停止的棒球", blurb: "运动的球怎样突然停住：惯性与力。", duration: "约 10 分钟", link: "https://www.bilibili.com/video/BV1AU4y1p7o5/?p=5", hints: ["惯性", "力", "停止"] },
        { id: "bigscience-6", n: 6, title: "不想移动的苹果", blurb: "静静待着的苹果，其实也在「对抗」。", duration: "约 10 分钟", link: "https://www.bilibili.com/video/BV1AU4y1p7o5/?p=6", hints: ["静止", "摩擦", "力"] },
      ],
    },
    {
      id: "planet",
      title: "地球脉动 第一季",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50–60 分钟 × 11 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      blurb: "从极地到深海的地球故事。画面震撼，像给地球办一场「超级相册」。",
      link: "https://www.bilibili.com/bangumi/play/ep121262",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧；高清常见需大会员",
      mapPin: "从极地到深海",
    },
    {
      id: "greenplanet",
      title: "绿色星球",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 6 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      blurb: "植物也会「打架、合作、求偶」。大卫·爱登堡带你用延时摄影看见被忽略的森林与沙漠。",
      link: "https://www.bilibili.com/bangumi/play/ep451881",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧；从第1集《雨林天地》起；高清常需大会员",
      mapPin: "植物 · 雨林到沙漠",
    },
    {
      id: "ourplanet",
      title: "我们的星球",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 8 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      blurb: "Netflix 与 BBC 联手：从冰原到深海，讲物种与家园，也点到气候与保护，画面接近《地球脉动》。",
      link: "https://www.bilibili.com/video/BV1Yz4y1z7Nx/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "第一季 8 集合集投稿；分P选集；清晰度看版本",
      mapPin: "全球 · 物种与家园",
    },
    {
      id: "blueplanet",
      title: "蓝色星球 第一季",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 8 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      blurb: "潜入海洋：洋流、珊瑚、深潜生物。经典自然大片，和《地球脉动》一样适合「周末只追一集」。",
      link: "https://www.bilibili.com/bangumi/play/ep119264",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧；高清常见需大会员",
      mapPin: "海洋 · 从浅滩到深渊",
    },
    {
      id: "frozen",
      title: "冰冻星球",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 6 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      blurb: "极地一年四季：冰、企鹅、北极熊。画面强，也适合聊「冰为什么在变」。",
      link: "https://www.bilibili.com/video/BV13Q4y1K74c/?p=1",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "国语合集 6 集分P；清晰度看版本",
      mapPin: "极地 · 四季",
      episodes: [
        { id: "frozen-1", n: 1, title: "世界的尽头", blurb: "北极和南极有多冷、谁住在冰上。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV13Q4y1K74c/?p=1", hints: ["极地", "冰", "适应"] },
        { id: "frozen-2", n: 2, title: "春季", blurb: "冰开始化，生命赶紧抓住短短的春天。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV13Q4y1K74c/?p=2", hints: ["融化", "繁殖", "赶时间"] },
        { id: "frozen-3", n: 3, title: "夏季", blurb: "极地的夏天：短暂、忙碌、食物最多。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV13Q4y1K74c/?p=3", hints: ["夏天", "觅食", "阳光"] },
        { id: "frozen-4", n: 4, title: "秋季", blurb: "冬天要来了，动物怎样准备迁徙或囤能。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV13Q4y1K74c/?p=4", hints: ["准备", "迁徙", "储存"] },
        { id: "frozen-5", n: 5, title: "冬季", blurb: "最难熬的季节：黑暗、风暴、怎样活下去。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV13Q4y1K74c/?p=5", hints: ["黑暗", "风暴", "忍耐"] },
        { id: "frozen-6", n: 6, title: "最后的边疆", blurb: "人与极地：科学站、气候变化，冰在说什么。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV13Q4y1K74c/?p=6", hints: ["气候", "变化", "保护"] },
      ],
    },
    {
      id: "wildchina",
      title: "美丽中国",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 6 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      blurb: "BBC×央视：从华南到高原、塞外到海滨。地理风景片，也是「中国长什么样」。",
      link: "https://www.bilibili.com/video/BV1yb4y147zE/?p=1",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "2011 年版 6 集分P",
      mapPin: "中国大地 · 自然",
      episodes: [
        { id: "wildchina-1", n: 1, title: "锦绣华南", blurb: "喀斯特、稻田、熊猫故乡：湿润的南方。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1yb4y147zE/?p=1", hints: ["华南", "山水", "多样"] },
        { id: "wildchina-2", n: 2, title: "云翔天边", blurb: "云贵高原：垂直气候、多彩民族与野生动物。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1yb4y147zE/?p=2", hints: ["高原", "云", "多样"] },
        { id: "wildchina-3", n: 3, title: "神奇高原", blurb: "青藏：高寒、稀薄空气，生命怎样站住。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1yb4y147zE/?p=3", hints: ["青藏", "高寒", "适应"] },
        { id: "wildchina-4", n: 4, title: "风雪塞外", blurb: "长城以北：草原、沙漠、迁徙的蹄。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1yb4y147zE/?p=4", hints: ["塞外", "草原", "风雪"] },
        { id: "wildchina-5", n: 5, title: "沃土中原", blurb: "黄河与耕地：人怎样把平原变成粮仓。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1yb4y147zE/?p=5", hints: ["中原", "黄河", "农耕"] },
        { id: "wildchina-6", n: 6, title: "潮涌两岸", blurb: "海岸线：渔、红树林、人和海怎么相处。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1yb4y147zE/?p=6", hints: ["海岸", "潮汐", "渔"] },
      ],
    },
    {
      id: "humanbody",
      title: "人体奥秘",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 4–6 集",
      episodeHint: "第 1、含临终/胚胎类集家长陪看",
      muscle: "人体",
      blurb: "钻进身体内部看心跳、细胞与成长。现用同题材《人体大惊奇》合集，挑一集即可。",
      link: "https://www.bilibili.com/video/BV1Sg411371W/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "BBC 原片投稿现少；改用同题材 PBS《人体大惊奇》6 集合集，挑 1 集",
      mapPin: "身体内部",
      parentNote: "胚胎与临终类镜头仍可能出现，家长陪看",
    },
    {
      id: "life",
      title: "生命",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 10 集",
      episodeHint: "先看植物、鸟、鱼",
      muscle: "生物",
      blurb: "动物植物怎么活下来：伪装、迁徙、育儿。比「好看」更进一步，讲生存策略。",
      link: "https://www.bilibili.com/bangumi/play/ep118932",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧；高清可能要会员",
      mapPin: "物种怎么活",
    },
    {
      id: "germsquad",
      title: "细菌病毒特工队",
      category: "nature",
      slot: "A",
      role: "main",
      duration: "约 5–8 分钟 / 集",
      episodeHint: "一晚 1–2 集",
      muscle: "生物",
      blurb: "流感、酵母、乳酸菌……用孩子能懂的故事走进细菌和病毒，顺带养成洗手习惯。",
      link: "https://www.bilibili.com/video/BV12h411V7Gv/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "少儿微生物科普合集，分P选集；短、适合工作日",
      mapPin: "细菌 · 病毒 · 卫生",
      episodes: [
        {
          id: "germsquad-1",
          n: 1,
          title: "流感病毒",
          blurb: "感冒为什么容易传开？流感病毒怎样钻进身体。",
          duration: "约 7 分钟",
          link: "https://www.bilibili.com/video/BV12h411V7Gv/?p=1",
          hints: ["飞沫", "传染", "洗手", "休息"],
        },
        {
          id: "germsquad-2",
          n: 2,
          title: "黄曲霉",
          blurb: "长毛的馒头还能吃吗？霉菌喜欢怎样的环境。",
          duration: "约 7 分钟",
          link: "https://www.bilibili.com/video/BV12h411V7Gv/?p=2",
          hints: ["发霉", "潮湿", "变质", "别吃坏掉的食物"],
        },
        {
          id: "germsquad-3",
          n: 3,
          title: "狂犬病毒",
          blurb: "被狗咬伤为什么要重视？狂犬病防范小知识。",
          duration: "约 7 分钟",
          link: "https://www.bilibili.com/video/BV12h411V7Gv/?p=3",
          hints: ["伤口", "疫苗", "告诉大人", "安全距离"],
        },
        {
          id: "germsquad-4",
          n: 4,
          title: "酵母菌",
          blurb: "面包为什么能发起来？酵母是「好帮手」微生物。",
          duration: "约 7 分钟",
          link: "https://www.bilibili.com/video/BV12h411V7Gv/?p=4",
          hints: ["发酵", "二氧化碳", "面团", "有用的菌"],
        },
        {
          id: "germsquad-5",
          n: 5,
          title: "乳酸菌",
          blurb: "牛奶的好朋友：酸奶里的菌怎样工作。",
          duration: "约 8 分钟",
          link: "https://www.bilibili.com/video/BV12h411V7Gv/?p=5",
          hints: ["酸奶", "发酵", "肠道", "有益菌"],
        },
        {
          id: "germsquad-6",
          n: 6,
          title: "醋酸菌",
          blurb: "醋是怎么来的？醋酸菌把酒变成酸酸的味道。",
          duration: "约 8 分钟",
          link: "https://www.bilibili.com/video/BV12h411V7Gv/?p=6",
          hints: ["醋", "发酵", "变酸", "食物加工"],
        },
        {
          id: "germsquad-7",
          n: 7,
          title: "草履虫",
          blurb: "水里的分解小工：草履虫怎样「打扫」污染物。",
          duration: "约 8 分钟",
          link: "https://www.bilibili.com/video/BV12h411V7Gv/?p=7",
          hints: ["微观", "单细胞", "分解", "水环境"],
        },
        {
          id: "germsquad-8",
          n: 8,
          title: "食用菌",
          blurb: "蘑菇亦正亦邪：能吃的菌和要小心的菌。",
          duration: "约 10 分钟",
          link: "https://www.bilibili.com/video/BV12h411V7Gv/?p=8",
          hints: ["蘑菇", "真菌", "别乱采", "辨认"],
        },
        {
          id: "germsquad-9",
          n: 9,
          title: "毛霉",
          blurb: "毛霉是谁？和食物、发酵有什么关系。",
          duration: "约 8 分钟",
          link: "https://www.bilibili.com/video/BV12h411V7Gv/?p=9",
          hints: ["霉菌", "发酵食品", "环境", "观察"],
        },
      ],
    },
    {
      id: "pasteur",
      title: "超级巴斯德",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 25–30 分钟 × 6 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      blurb: "跟着巴斯德闯微生物世界：发酵、疫苗、致病菌。动画讲故事，四年级跟得上。",
      link: "https://www.bilibili.com/video/BV1NExtzNEgE/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "央视趣味科普，6 集合一投稿；可按进度分段看",
      mapPin: "微生物 · 实验与发现",
    },
    {
      id: "bodymicro",
      title: "人体的微观世界",
      category: "nature",
      slot: "B",
      role: "main",
      duration: "约 40 分钟 × 8 集",
      episodeHint: "周末 1 集 · 可先看信号分子 / 肠道",
      muscle: "人体",
      blurb: "镜头钻进细胞、免疫与器官：显微摄影 + 动画，像科幻片一样看身体内部。",
      link: "https://www.bilibili.com/video/BV1R22nBeEpE/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "8 集分P；对细胞感兴趣从第1集「信号分子」起",
      mapPin: "细胞 · 免疫 · 器官",
    },
    {
      id: "cellwar",
      title: "细胞的暗战",
      category: "nature",
      slot: "B",
      role: "side",
      duration: "约 50–60 分钟",
      episodeHint: "周末一部 · 可拆两晚",
      muscle: "人体",
      blurb: "细胞怎样「打仗」保卫身体。聚焦微观战场，补足对细胞机制的好奇心。",
      link: "https://www.bilibili.com/video/BV1L44y1B789/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "《人体的奥秘》细胞篇双语投稿",
      mapPin: "细胞 · 攻防",
    },
    {
      id: "bacteriasecret",
      title: "破解细菌的秘密",
      category: "nature",
      slot: "A",
      role: "side",
      duration: "约 58 分钟",
      episodeHint: "可拆两晚 · 或周末加餐",
      muscle: "生物",
      blurb: "从列文虎克的显微镜到巴斯德、科赫：人类怎么一步步看见细菌。央视《解码科技史》。",
      link: "https://www.bilibili.com/video/BV1c3411Q7Gx/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "单集约 1 小时；亦可在央视网搜同名",
      mapPin: "显微镜 · 细菌史",
      altLink: "https://tv.cctv.com/2022/11/13/VIDEysn1jha46UFtJZVVmNhy221113.shtml",
      altLabel: "央视网",
    },
    {
      id: "microcosmos",
      title: "微观世界",
      category: "nature",
      slot: "B",
      role: "side",
      duration: "约 25 分钟 × 5 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      blurb: "草叶下的昆虫「王国」：放大到能看见触角上的水珠。微观尺度的自然大片。",
      link: "https://www.bilibili.com/video/BV1E5411M7uT/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "央视 HD 5 集合集；偏昆虫微距，培养「看不见的世界」直觉",
      mapPin: "微距 · 昆虫世界",
    },
    {
      id: "wonders",
      title: "生命的奇迹",
      category: "nature",
      slot: "B",
      role: "side",
      duration: "约 48–60 分钟 × 5 集",
      episodeHint: "周末 1 集",
      muscle: "生物",
      blurb: "物理学家追问：生命到底是什么？把生物和能量、宇宙规律连在一起想。",
      link: "https://www.bilibili.com/video/BV1Uw411d7xw/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "国语合集直链；周末只看 1 集",
      mapPin: "生命是什么",
    },
    {
      id: "guobao",
      title: "如果国宝会说话",
      category: "human",
      slot: "A",
      role: "main",
      duration: "5 分钟，一晚 2–3 集",
      episodeHint: "打包 2–3 集",
      muscle: "审美",
      blurb: "一件国宝讲一个小故事：形状、纹样、工艺。短片累加，养「看得懂物件」的眼睛。",
      link: "https://www.bilibili.com/bangumi/play/ep165008",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版番剧，页面标高清",
      mapPin: "博物馆 · 形与工艺",
    },
    {
      id: "qimiao",
      title: "奇妙中国",
      category: "human",
      slot: "A",
      role: "side",
      duration: "短片 × 10 集（第一季）",
      episodeHint: "一晚 1–2 集",
      muscle: "叙事",
      blurb: "一集一个中国「奇妙」：物产、手艺、自然奇观。短、信息密，适合工作日加餐。",
      link: "https://www.bilibili.com/video/BV17gopBPE8Y/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "第一季 10 集合集；分P选集",
      mapPin: "中国 · 物产与手艺",
    },
    {
      id: "letters",
      title: "书简阅中国",
      category: "human",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 6 集",
      episodeHint: "周末 1 集 · 可先看第1集家书",
      muscle: "叙事",
      blurb: "一封信一个故事：家书、友情、家风。用古人的字，看见他们怎么爱、怎么选、怎么活。",
      link: "https://tv.cctv.com/2021/02/12/VIDE6castX10rFlwYX7KPvLb210212.shtml",
      linkLabel: "央视网",
      play: "stable",
      playNote: "央视网正片 6 集；手机建议央视影音 App",
      mapPin: "书信 · 人情与选择",
      parentNote: "第2集爱情、第4集女性命运，建议家长陪看",
      altLink: "https://tv.cctv.com/2021/02/08/VIDAHc9krezHR6EXJAq7w0nM210208.shtml",
      altLabel: "节目目录",
      episodes: [
        {
          id: "letters-1",
          n: 1,
          title: "小人物 大历史",
          blurb: "家书连着游子：小人物的字，记下大历史里的温度。",
          duration: "约 50 分钟",
          link: "https://tv.cctv.com/2021/02/12/VIDE6castX10rFlwYX7KPvLb210212.shtml",
          hints: ["家书", "亲人", "小人物", "文字留下温度"],
        },
        {
          id: "letters-2",
          n: 2,
          title: "是你告诉我 爱情的模样",
          blurb: "秦嘉徐淑、卓文君……信里怎么写「喜欢」和「牵挂」。",
          duration: "约 50 分钟",
          link: "https://tv.cctv.com/2021/02/13/VIDEL0urlbjetiiqviqnzEy5210213.shtml",
          hints: ["书信", "牵挂", "表达", "家长陪看"],
        },
        {
          id: "letters-3",
          n: 3,
          title: "再大的风 我都去接你",
          blurb: "知己难寻：嵇康与山涛、白居易与元稹，友情写在信上。",
          duration: "约 50 分钟",
          link: "https://tv.cctv.com/2021/02/14/VIDEva10ohfmFstDIZA0kC2o210214.shtml",
          hints: ["友情", "知己", "成全", "不同意见也能尊重"],
        },
        {
          id: "letters-4",
          n: 4,
          title: "孤独的路 勇敢的心",
          blurb: "信里看见女子怎样走路：被限制，也仍要发出自己的声音。",
          duration: "约 50 分钟",
          link: "https://tv.cctv.com/2021/02/15/VIDEtIs6s13W5TClAnByTI6W210215.shtml",
          hints: ["勇气", "选择", "发出声音", "家长陪看"],
        },
        {
          id: "letters-5",
          n: 5,
          title: "千古栋梁有家风",
          blurb: "刘邦、马援、范仲淹……一封家书，怎样把规矩和期待传给后人。",
          duration: "约 50 分钟",
          link: "https://tv.cctv.com/2021/02/16/VIDEJvIlGsVBA70OOP4rXbIw210216.shtml",
          hints: ["家风", "规矩", "期待", "写信给孩子"],
        },
        {
          id: "letters-6",
          n: 6,
          title: "留取丹心照汗青",
          blurb: "岳飞、文天祥、林则徐：危难时，信里写出的志向。",
          duration: "约 50 分钟",
          link: "https://tv.cctv.com/2021/02/17/VIDEBRjhgVJe5XUcksE8DYOU210217.shtml",
          hints: ["志向", "家国", "危难", "丹心"],
        },
      ],
    },
    {
      id: "zicong",
      title: "字从遇见你",
      category: "human",
      slot: "A",
      role: "main",
      duration: "约 5 分钟 / 集",
      episodeHint: "一晚 2–3 个字",
      muscle: "审美",
      blurb: "一集一个汉字：中、鼎、友……字形从哪来、古人怎么用。短，很适合工作日。",
      link: "https://tv.cctv.com/2022/04/03/VIDE7qRtbkEOj7Q0M7FwKNDS220403.shtml",
      linkLabel: "央视网",
      play: "stable",
      playNote: "第一季每集一字；目录可换字继续看",
      mapPin: "汉字 · 形与故事",
      altLink: "https://tv.cctv.com/2022/04/04/VIDACO0Ql6L8Q7t41qzriSTy220404.shtml",
      altLabel: "节目目录",
      episodes: [
        { id: "zicong-1", n: 1, title: "中", blurb: "汉字世界的中心：旗帜、「中国」一词从哪来。", duration: "约 5 分钟", link: "https://tv.cctv.com/2022/04/03/VIDE7qRtbkEOj7Q0M7FwKNDS220403.shtml", hints: ["中心", "甲骨", "何尊"] },
        { id: "zicong-2", n: 2, title: "鼎", blurb: "一只鼎：礼器、权力，和一个字的分量。", duration: "约 5 分钟", link: "https://tv.cctv.com/2022/04/04/VIDACO0Ql6L8Q7t41qzriSTy220404.shtml", hints: ["青铜", "礼器", "分量"] },
        { id: "zicong-3", n: 3, title: "卜", blurb: "古人怎样问天：甲骨上的裂纹变成了字。", duration: "约 5 分钟", link: "https://tv.cctv.com/2022/04/04/VIDACO0Ql6L8Q7t41qzriSTy220404.shtml", hints: ["甲骨", "占卜", "裂纹"] },
        { id: "zicong-4", n: 4, title: "天", blurb: "人仰头看见的「天」：字里藏着崇拜与秩序。", duration: "约 5 分钟", link: "https://tv.cctv.com/2022/04/04/VIDACO0Ql6L8Q7t41qzriSTy220404.shtml", hints: ["天空", "仰观", "秩序"] },
        { id: "zicong-5", n: 5, title: "福", blurb: "「福」字怎么写：酒、田、祈愿。", duration: "约 5 分钟", link: "https://tv.cctv.com/2022/04/04/VIDACO0Ql6L8Q7t41qzriSTy220404.shtml", hints: ["祈愿", "酒", "田"] },
      ],
    },
    {
      id: "heyi",
      title: "何以中国",
      category: "human",
      slot: "B",
      role: "side",
      duration: "约 50 分钟 × 8 集",
      episodeHint: "周末 1 集 · 可先看《秦汉》",
      muscle: "叙事",
      blurb: "用考古回答「中国从哪来」：秦汉一统，再往回走到摇篮与古国。家长可陪看。",
      link: "https://www.iqiyi.com/a_25yb25rmy3t.html",
      linkLabel: "爱奇艺正版",
      play: "stable",
      playNote: "8 集全；在爱奇艺选集。考古向，四年级挑感兴趣的集",
      mapPin: "考古 · 文明从哪来",
      parentNote: "信息密、偏成人叙事，建议陪看一集再决定追不追",
      episodes: [
        { id: "heyi-1", n: 1, title: "秦汉", blurb: "第一个统一的中国：律法、道路、认同怎样立住。", duration: "约 50 分钟", link: "https://www.iqiyi.com/a_25yb25rmy3t.html", hints: ["统一", "秦", "汉"] },
        { id: "heyi-2", n: 2, title: "摇篮", blurb: "农业与定居：人怎样从流动变成「住下来」。", duration: "约 50 分钟", link: "https://www.iqiyi.com/a_25yb25rmy3t.html", hints: ["农业", "定居", "起源"] },
        { id: "heyi-3", n: 3, title: "星斗", blurb: "彩陶与交流：各地怎样开始大规模互动。", duration: "约 50 分钟", link: "https://www.iqiyi.com/a_25yb25rmy3t.html", hints: ["彩陶", "交流", "互动"] },
        { id: "heyi-4", n: 4, title: "古国", blurb: "早期国家出现：长江、黄河、西辽河的「古国」。", duration: "约 50 分钟", link: "https://www.iqiyi.com/a_25yb25rmy3t.html", hints: ["古国", "早期文明"] },
        { id: "heyi-5", n: 5, title: "择中", blurb: "中原怎样成为「中」：广域王朝的诞生。", duration: "约 50 分钟", link: "https://www.iqiyi.com/a_25yb25rmy3t.html", hints: ["中原", "王朝"] },
        { id: "heyi-6", n: 6, title: "殷商", blurb: "甲骨与青铜：商代留下的字和器。", duration: "约 50 分钟", link: "https://www.iqiyi.com/a_25yb25rmy3t.html", hints: ["甲骨", "青铜", "商"] },
        { id: "heyi-7", n: 7, title: "家国", blurb: "家与国怎样连在一起：周代的秩序想象。", duration: "约 50 分钟", link: "https://www.iqiyi.com/a_25yb25rmy3t.html", hints: ["家", "国", "周"] },
        { id: "heyi-8", n: 8, title: "天下", blurb: "多元一体：许多地方怎样变成一个「天下」。", duration: "约 50 分钟", link: "https://www.iqiyi.com/a_25yb25rmy3t.html", hints: ["天下", "多元", "一体"] },
      ],
    },
    {
      id: "histfun",
      title: "历史那些事",
      category: "human",
      slot: "A",
      role: "side",
      duration: "约 25–30 分钟 / 集",
      episodeHint: "工作日或周末 1 集",
      muscle: "叙事",
      blurb: "苏轼爱吃、乾隆爱批奏折……正史里的趣事，轻松入口，不像通史那么沉。",
      link: "https://www.bilibili.com/video/BV1mG41197jz/?p=1",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "合集含多集；先看「在下东坡」",
      mapPin: "趣味正史",
      episodes: [
        { id: "histfun-1", n: 1, title: "在下东坡 一个吃货", blurb: "苏轼不只会写诗：东坡肉、贬谪路上的胃口。", duration: "约 25 分钟", link: "https://www.bilibili.com/video/BV1mG41197jz/?p=1", hints: ["苏轼", "吃", "乐观"] },
        { id: "histfun-2", n: 2, title: "请回答604", blurb: "隋唐之间的一则「穿越感」小史。", duration: "约 25 分钟", link: "https://www.bilibili.com/video/BV1mG41197jz/?p=2", hints: ["隋唐", "故事"] },
        { id: "histfun-3", n: 3, title: "爱发弹幕的乾隆同学", blurb: "乾隆爱在书画上题字：古人的「弹幕」。", duration: "约 25 分钟", link: "https://www.bilibili.com/video/BV1mG41197jz/?p=3", hints: ["乾隆", "题字", "趣味"] },
      ],
    },
    {
      id: "designah",
      title: "啊！设计",
      category: "human",
      slot: "A",
      role: "side",
      duration: "约 15 分钟",
      episodeHint: "工作日加餐 · 只看 1 集",
      muscle: "审美",
      blurb: "拆雨伞、铅笔、书包：日常物件原来是这样设计的。观察力训练，很适合四年级。",
      link: "https://www.bilibili.com/video/BV1hwKfzmEr4/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "60 集合集直链；当晚只看 1 集",
      mapPin: "观察 · 拆解",
    },
    {
      id: "aerial",
      title: "航拍中国 第一季",
      category: "human",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 6 集",
      episodeHint: "周末 1 集",
      muscle: "叙事",
      blurb: "从天上俯瞰中国山川城市。构图漂亮，也适合聊「地方长什么样、人怎么住」。",
      link: "https://tv.cctv.com/2016/12/28/VIDALOmjxOZe51NjntPvOI00161228.shtml",
      linkLabel: "央视网",
      play: "stable",
      playNote: "央视网官方；手机建议央视影音 App",
      mapPin: "中国大地 · 构图",
    },
    {
      id: "supereng",
      title: "超级工程",
      category: "finance",
      slot: "B",
      role: "main",
      duration: "约 40–50 分钟 / 集",
      episodeHint: "周末 1 集 · 优先大桥 / 大厦 / 隧道",
      muscle: "数理",
      blurb: "不利条件下怎么把活干完：港珠澳沉管、上海中心抗震、隧道防水。看工程师怎么解题。",
      link: "https://www.bilibili.com/video/BV1x7411j7sc/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "央视《超级工程》合集；先挑港珠澳、上海中心、隧道类集",
      mapPin: "难题 · 材料 · 精度",
      altLink: "https://www.bilibili.com/video/BV1gW411o7PZ/",
      altLabel: "第二季入口（路/桥/港）",
    },
    {
      id: "howmade",
      title: "造物小百科",
      category: "finance",
      slot: "A",
      role: "main",
      duration: "约 5–8 分钟 / 段",
      episodeHint: "一晚 1 个工厂片段",
      muscle: "数理",
      blurb: "铝箔、蜂蜜、牛仔裤怎么从工厂里出来。接材料片：看见「东西是被做出来的」。",
      link: "https://www.bilibili.com/video/BV1HPMP6vE4x/?p=1",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "How It's Made 第一季中字；当晚只看 1 段（一集里常有 4 个小物）",
      mapPin: "工厂 · 怎么做出来",
      episodes: [
        { id: "howmade-1", n: 1, title: "铝箔 · 滑雪板 · 镜片 · 面包", blurb: "四种日常物的生产线：从原料到成品。", duration: "约 22 分钟", link: "https://www.bilibili.com/video/BV1HPMP6vE4x/?p=1", hints: ["铝箔", "生产线", "步骤"] },
        { id: "howmade-2", n: 2, title: "光碟 · 奶酪 · 丝袜 · 灯管", blurb: "光滑、柔软、发光：材料被怎样加工。", duration: "约 22 分钟", link: "https://www.bilibili.com/video/BV1HPMP6vE4x/?p=2", hints: ["加工", "成型"] },
        { id: "howmade-3", n: 3, title: "牙签 · 浴缸 · 直升机 · 啤酒", blurb: "从很小到很大：尺度一变，工艺也变。", duration: "约 22 分钟", link: "https://www.bilibili.com/video/BV1HPMP6vE4x/?p=3", hints: ["尺度", "工艺"] },
        { id: "howmade-4", n: 4, title: "助听器 · 拼图 · 马桶", blurb: "精密小零件和家里的大家伙，怎么被做准。", duration: "约 22 分钟", link: "https://www.bilibili.com/video/BV1HPMP6vE4x/?p=4", hints: ["精度", "模具"] },
        { id: "howmade-5", n: 5, title: "复印纸 · 牛仔裤 · 电脑 · 玻璃", blurb: "纸、布、芯片、玻璃：四种完全不同的「造」。", duration: "约 22 分钟", link: "https://www.bilibili.com/video/BV1HPMP6vE4x/?p=5", hints: ["纸", "布", "玻璃"] },
        { id: "howmade-6", n: 6, title: "钉子 · 护目镜 · 布匹 · 自行车", blurb: "钉子和自行车：简单零件怎样变成能骑的车。", duration: "约 22 分钟", link: "https://www.bilibili.com/video/BV1HPMP6vE4x/?p=6", hints: ["零件", "组装"] },
      ],
    },
    {
      id: "materialsecret",
      title: "材料的秘密身世",
      category: "finance",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 3 集",
      episodeHint: "周末 1 集（已看过第1可续第2）",
      muscle: "数理",
      blurb: "金属、塑料、陶瓷……日常材料从哪来、改变了什么。故事感强，比纯工业片更好入口。",
      link: "https://www.bilibili.com/bangumi/play/ep257923",
      linkLabel: "B 站正版",
      play: "stable",
      playNote: "正版 3 集；建议家长陪看第 1 集建立兴趣",
      mapPin: "材料 · 从矿石到生活",
      episodes: [
        {
          id: "materialsecret-1",
          n: 1,
          title: "金属",
          blurb: "从青铜到合金：金属怎样被冶炼，又怎样撑起飞机与城市。",
          duration: "约 50 分钟",
          link: "https://www.bilibili.com/bangumi/play/ep257923",
          hints: ["冶炼", "合金", "坚硬与延展", "工具与建筑"],
        },
        {
          id: "materialsecret-2",
          n: 2,
          title: "塑料",
          blurb: "塑料如何模仿自然、走进日常，也带来新的问题与可能。",
          duration: "约 50 分钟",
          link: "https://www.bilibili.com/bangumi/play/ep257924",
          hints: ["聚合物", "轻便", "大量生产", "回收与使用"],
        },
        {
          id: "materialsecret-3",
          n: 3,
          title: "陶瓷",
          blurb: "黏土、沙子变成陶器、玻璃和水泥：平凡材料如何建起文明。",
          duration: "约 50 分钟",
          link: "https://www.bilibili.com/bangumi/play/ep257925",
          hints: ["陶瓷", "玻璃", "水泥", "耐热与透明"],
        },
      ],
    },
    {
      id: "qingzang",
      title: "青藏铁路",
      category: "finance",
      slot: "B",
      role: "main",
      duration: "约 40 分钟 × 6 集",
      episodeHint: "周末 1 集 · 建议冻土 / 高海拔集",
      muscle: "数理",
      blurb: "世界屋脊上修铁路：缺氧、冻土、塌方。极端环境里怎么把问题解决掉。",
      link: "https://www.bilibili.com/video/BV1fs411o7Yn/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "全 6 集分P；可先看冻土与桥梁难题集",
      mapPin: "高原 · 冻土 · 解题",
    },
    {
      id: "antarcticbase",
      title: "南极极端基地",
      category: "finance",
      slot: "B",
      role: "side",
      duration: "约 45 分钟",
      episodeHint: "周末一部",
      muscle: "数理",
      blurb: "极寒、移动冰层、狂风：南极科考站怎么站住、怎么保暖、物资怎么运到。极限建造故事。",
      link: "https://www.bilibili.com/video/BV1Rdb36vEB8/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "中配合集向短片；看「环境难题→工程对策」",
      mapPin: "南极 · 抗风抗寒",
    },
    {
      id: "skytree",
      title: "东京天空树",
      category: "finance",
      slot: "B",
      role: "side",
      duration: "约 45–50 分钟",
      episodeHint: "周末一部",
      muscle: "数理",
      blurb: "又高又要抗震：钢材怎么接、工地怎么组织。一座塔如何在地震带「站住」。",
      link: "https://www.bilibili.com/video/BV15s411Z7Qz/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "NHK 建造历程；偏工程过程，不是学院审美片",
      mapPin: "高度 · 抗震解题",
    },
    {
      id: "bridges",
      title: "跨越（桥梁）",
      category: "finance",
      slot: "B",
      role: "side",
      duration: "约 45 分钟 × 5 集",
      episodeHint: "周末 1 集",
      muscle: "数理",
      blurb: "桥为什么不会塌？梁桥、拱桥、斜拉桥怎么把力传到地面。材料与力学入门。",
      link: "https://www.bilibili.com/video/BV1Rt411t7qv/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "央视《跨越》桥梁建设系列",
      mapPin: "桥梁 · 力的路径",
    },
    {
      id: "dimensions",
      title: "维度：数学漫步（第1–2章）",
      category: "finance",
      slot: "A",
      role: "main",
      duration: "约 14 分钟 / 章",
      episodeHint: "只看二维、三维",
      muscle: "数理",
      blurb: "用动画走进二维、三维空间。为建筑平面图、立体结构打一点直觉基础。",
      link: "https://www.dimensions-math.org/Dim_ZH_si.htm",
      linkLabel: "官网免费正片",
      play: "stable",
      playNote: "创作共用，官网可看可下，画质清晰",
      mapPin: "空间直觉",
    },
    {
      id: "thecode",
      title: "解码数学",
      category: "finance",
      slot: "B",
      role: "main",
      duration: "约 50 分钟 × 3 集",
      episodeHint: "周末 1 集 · 可先看「形状」",
      muscle: "数理",
      blurb: "数字、形状、预测：自然和建筑里藏着的「密码」。四年级数学格的好入口。",
      link: "https://www.bilibili.com/video/BV1Mx411R7oQ/?p=1",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "BBC The Code 全 3 集分P",
      mapPin: "数字 · 形状 · 预测",
      episodes: [
        { id: "thecode-1", n: 1, title: "数字", blurb: "数字藏在自然和生活里：数一数，规律就出现。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1Mx411R7oQ/?p=1", hints: ["数字", "规律", "自然"] },
        { id: "thecode-2", n: 2, title: "形状", blurb: "形状为什么反复出现：蜂巢、建筑、雪花。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1Mx411R7oQ/?p=2", hints: ["形状", "建筑", "重复"] },
        { id: "thecode-3", n: 3, title: "预测", blurb: "用数学猜下一步：天气、趋势、可能性。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1Mx411R7oQ/?p=3", hints: ["预测", "可能", "模型"] },
      ],
    },
    {
      id: "econmachine",
      title: "经济机器是怎样运行的",
      category: "finance",
      slot: "A",
      role: "main",
      duration: "约 30 分钟 × 1",
      episodeHint: "可工作日看完",
      muscle: "商业",
      blurb: "桥水基金用动画讲清：交易、借贷、周期。30 分钟建立「钱怎么流动」的骨架。",
      link: "https://www.bilibili.com/video/BV1HA411j7vH/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "约 30 分钟完整投稿；有字幕",
      mapPin: "交易 · 信贷 · 周期",
      altLink: "https://www.youtube.com/watch?v=rFV7wdEX-Mo",
      altLabel: "YouTube（备）",
    },
    {
      id: "surveil",
      title: "监视资本主义：智能陷阱",
      category: "drive",
      slot: "B",
      role: "side",
      duration: "约 90 分钟",
      episodeHint: "家长陪看 · 可拆两晚",
      muscle: "选择",
      blurb: "为什么总想刷手机？平台怎样用注意力赚钱。四年级须家长在场，一起讨论「谁在用我的时间」。",
      link: "https://www.bilibili.com/video/BV1jG411D7U5/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "即 The Social Dilemma；国语中配投稿，约 90 分钟",
      mapPin: "注意力 · 选择",
      parentNote: "题材偏成人（成瘾、数据、操控），必须家长陪看，不适合孩子单独打开",
    },
    {
      id: "logicjoy",
      title: "逻辑的乐趣",
      category: "finance",
      slot: "B",
      role: "side",
      duration: "约 60 分钟",
      episodeHint: "可拆两晚",
      muscle: "数理",
      blurb: "逻辑从哪里来、电脑为什么懂「是/否」。趣味讲解，帮孩子建立清晰思考。",
      link: "https://www.bilibili.com/video/BV1W3411y7Dc/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "约 60 分钟完整投稿",
      mapPin: "逻辑是什么",
    },
    {
      id: "newtoncoach",
      title: "我的牛顿教练",
      category: "finance",
      slot: "B",
      role: "main",
      duration: "约 25 分钟 × 6 集",
      episodeHint: "周末 1 集",
      muscle: "数理",
      blurb: "跑步、游泳、射箭……用运动讲牛顿定律：空气、速度、旋转与力量。央视科普，物理启蒙对口。",
      link: "https://www.bilibili.com/video/BV1Hx421U7V5/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "合集含多集分P；若缺集可搜「我的牛顿教练 央视」单集或央视网目录",
      mapPin: "运动 · 物理直觉",
      altLink: "https://tv.cctv.com/2018/06/26/VIDAAg8W6IxzkfUGlpl7CbsF180626.shtml",
      altLabel: "央视网（全6集）",
    },
    {
      id: "mathstory",
      title: "数学的故事（第1–2集）",
      category: "finance",
      slot: "B",
      role: "side",
      duration: "约 60 分钟 × 4（四年级看前 2）",
      episodeHint: "宇宙的语言 · 东方奇才",
      muscle: "数理",
      blurb: "数学从埃及、巴比伦走到东方：数字与几何怎么变成今天的工具。先看前两集。",
      link: "https://www.bilibili.com/video/BV1DZ421H7it/",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "第1集《宇宙的语言》直链；第2集可另找东方数学篇",
      mapPin: "数学史入口",
      altLink: "https://www.bilibili.com/video/BV1oa411E7wd/",
      altLabel: "第2集入口",
    },
    {
      id: "englishadv",
      title: "英语发展史",
      category: "human",
      slot: "B",
      role: "side",
      duration: "约 50 分钟 × 8 集",
      episodeHint: "周末 1 集 · 四年级可先听第1集",
      muscle: "叙事",
      blurb: "英语从日耳曼方言走到全球：词从哪来、为什么今天长这样。可当故事听，不必一次听懂所有词。",
      link: "https://www.bilibili.com/video/BV1vs41117JH/?p=1",
      linkLabel: "B 站直达",
      play: "ok",
      playNote: "ITV The Adventure of English 8 集分P；中字。信息密，可只追感兴趣的集",
      mapPin: "语言从哪来",
      parentNote: "节奏偏成人，建议陪看第1集再决定",
      episodes: [
        { id: "englishadv-1", n: 1, title: "语言的诞生", blurb: "英语从哪冒出来：部落、入侵、混出来的话。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1vs41117JH/?p=1", hints: ["起源", "混合", "词"] },
        { id: "englishadv-2", n: 2, title: "英语转入地下", blurb: "诺曼征服后：英语怎样「躲」过贵族法语。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1vs41117JH/?p=2", hints: ["征服", "法语", "地下"] },
        { id: "englishadv-3", n: 3, title: "圣经语言之争", blurb: "把圣经译成英语：谁有权读、用哪种词。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1vs41117JH/?p=3", hints: ["翻译", "圣经", "权利"] },
        { id: "englishadv-4", n: 4, title: "地球，大洲，英格兰", blurb: "莎士比亚前后：英语开始「长成」文学语言。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1vs41117JH/?p=4", hints: ["莎士比亚", "文学"] },
        { id: "englishadv-5", n: 5, title: "英语在美国", blurb: "漂过大洋：美国英语怎样走出自己的路。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1vs41117JH/?p=5", hints: ["美国", "口音", "新词"] },
        { id: "englishadv-6", n: 6, title: "流利口语", blurb: "「说得体面」：口音、阶层和学校。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1vs41117JH/?p=6", hints: ["口音", "阶层"] },
        { id: "englishadv-7", n: 7, title: "帝国的语言", blurb: "英语跟着船队走遍世界：贸易、殖民与传播。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1vs41117JH/?p=7", hints: ["传播", "贸易", "世界"] },
        { id: "englishadv-8", n: 8, title: "许多种英语", blurb: "今天的英语：很多口音、很多地方话，仍叫 English。", duration: "约 50 分钟", link: "https://www.bilibili.com/video/BV1vs41117JH/?p=8", hints: ["多样", "全球", "口音"] },
      ],
    },
  ],
};
